# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38b7630aed169a068fefea667503edef894dbaa45805b8fd60128d009fc8a204e057fb5d9deab8a680c4105e8a74e584fe033e7c62bf5e57fab10242d770ee9f

test:
  secret_key_base: 5f45cd723ad06a919a70e7cb5fb6692b1039d2948feca1ee85e3d18f5cf70f3a2f07f5c3830e3d45db7dbc30de3d5b16a1abe173a4accf98076a64d89c85147b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
